<script setup lang="ts">
    const runtimeConfig = useRuntimeConfig()
    const devMode = ref(runtimeConfig.public.devMode);
    const defaultUserName = ref(runtimeConfig.public.defaultUserName);
    const defaultUserPassword = ref(runtimeConfig.public.defaultUserPassword);

    const { loggedIn, user, fetch: refreshSession } = useUserSession()
    const credentials = reactive({
        email: devMode.value ? defaultUserName.value : '',
        password: devMode.value ? defaultUserPassword.value : '',
    })
    const loginError = ref(false)
    const loginErrorMessage = ref('')
    const formValid = ref(false)
    const isLoading = ref(false)

    async function login() {
        loginError.value = false
        loginErrorMessage.value = ''
        isLoading.value = true
        
        try {
            const res = await $fetch<{
                user: { name: string; email: string; role: 'Admin' | 'User' | undefined };
                success?: boolean;
                error?: boolean;
                // provide a concrete shape for data so TypeScript knows it may contain name and/or message
                data?: { name?: string; message?: unknown };
                message: string;
            }>('/api/auth/login', {
                method: 'POST',
                body: credentials
            })

            if (res?.success) {
                // Refresh the session on client-side and redirect to the home page
                await refreshSession()
                await navigateTo('/dashboard')
            } else {
                loginError.value = true
                loginErrorMessage.value = res?.message || 'Login failed. Please try again.'
            }
        } catch (error: any) {
            
            loginError.value = true
            loginErrorMessage.value = error?.data?.message || error?.message || 'Login failed. Please try again.'

            // Check if the error is an H3Error object generated by Zod
            if (error && error.data && error.data.data) {
                const errorObject = JSON.parse(error.data.message)
                const issues = Array.isArray(errorObject) ? errorObject : []
                loginErrorMessage.value = issues.length ? String(issues[0].message || issues[0]) : (error?.message || 'Invalid input')
            } 
        } finally {
            isLoading.value = false
        }
    }
</script>

<template>
    <v-card class="pa-5" max-width="400" min-width="300">
        <v-form ref="loginForm" v-model="formValid" @submit.prevent="login">
            <v-text-field
                v-model="credentials.email"
                label="Email"
                type="email"
                data-testid="email-input"
                placeholder="Email"
                required
                :rules="[(v: string) => !!v || 'Email is required', (v: string) => /.+@.+\..+/.test(v) || 'E-mail must be valid']"
                class="mb-4"
            />
            <v-text-field
                v-model="credentials.password"
                label="Password"
                type="password"
                data-testid="password-input"
                placeholder="Password"
                required
                :rules="[(v: string) => !!v || 'Password is required', (v: string) => v.length >= 8 || 'Password must be at least 8 characters']"
                class="mb-4"
            />
            <v-btn 
                :disabled="!formValid || isLoading" 
                :loading="isLoading"
                type="submit" 
                data-testid="login-submit-button"
                color="primary" 
                block
            >
                Login
            </v-btn>
        </v-form>
        <v-alert
            v-if="loginError"
            type="error"
            variant="tonal"
            class="mt-4"
            data-testid="login-error"
            :text="loginErrorMessage"
        />
        <div v-if="loggedIn" class="mt-4 text-center">
            <p>Welcome, {{ (user as any)?.name }}</p>
        </div>
        <div v-else-if="!loggedIn" class="mt-4 text-center">
            <p>Please log in</p>
            <p class="mt-2">
                Don't have an account? 
                <a href="/register" class="text-primary" data-testid="register-link">
                    Register here
                </a>
            </p>
        </div>
    </v-card>
</template>
